name: Linux Check Dependency
on:
  workflow_dispatch:

jobs:
  build:
    name: Release Sync
    if: ${{ github.event.workflow_run.conclusion == 'success' }} || ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout current repo
      uses: actions/checkout@v4
      with:
        submodules: false
        path: "current_repo"
    - name: Print Dependency
      working-directory: ./current_repo
      run: python3 linux_check.py